### ISSUE TITLE
Small problem with translating messages.yml

### ISSUE THREAD

**Issue by Haker519** [TechFortress/GriefPrevention#983]
Hey team!

Didn`t find any informations in FAQ.

I have small problem with translating file messages.yml.

Downloaded this, opened with Notepad++ and doin` my things.
To check results, after almost 150 lines i saved file and droped on serwer (when server was offline of course). 

Turning on my server and...
Everything is still in english - my translated file is just renewed with english one (basic, original).

Any ideas why?

**Comment by Jikoo** [comment]
Probably a syntax error in your yaml, check your startup logs.

**Comment by bigpreshkt** [comment]
As Jikoo says, probably a syntax error in the YAML (in which case GP will warn about it in the logs, and fall back to the default messages), so look in your logs for clues, and/or feed your modified YAML through `yamllint` or some online YAML linter/validator to see what's wrong with it.

**Comment by Haker519** [comment]
You are right. 
Firtly i was thinking that some letters are not allowed, but when changed for original i get this.
Any ideas how to fix this? Propably this fail is forcing plugin to renew messages.yml for original



[22:11:07] [Server thread/INFO]: [GriefPrevention] Enabling GriefPrevention v16.13.0
[22:11:07] [Server thread/INFO]: [GriefPrevention] Finished loading configuration.
[22:11:07] [Server thread/INFO]: [GriefPrevention] 2 total claims loaded.
[22:11:07] [Server thread/ERROR]: Cannot load plugins/GriefPreventionData/messages.yml
org.bukkit.configuration.InvalidConfigurationException: mapping values are not allowed here
 in 'string', line 36, column 9:
        Text: Stand inside the claim you're  ... 
            ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:56) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:160) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:128) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:183) ~[patched_1.15.2.jar:git-Paper-379]
	at me.ryanhamshire.GriefPrevention.DataStore.loadMessages(DataStore.java:1692) ~[?:?]
	at me.ryanhamshire.GriefPrevention.DataStore.initialize(DataStore.java:158) ~[?:?]
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.initialize(FlatFileDataStore.java:215) ~[?:?]
	at me.ryanhamshire.GriefPrevention.FlatFileDataStore.<init>(FlatFileDataStore.java:63) ~[?:?]
	at me.ryanhamshire.GriefPrevention.GriefPrevention.onEnable(GriefPrevention.java:314) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-379]
	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-379]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_201]
Caused by: org.yaml.snakeyaml.scanner.ScannerException: mapping values are not allowed here
 in 'string', line 36, column 9:
        Text: Stand inside the claim you're  ... 
            ^

	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchValue(ScannerImpl.java:870) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:358) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.scanner.ScannerImpl.checkToken(ScannerImpl.java:227) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockMappingKey.produce(ParserImpl.java:558) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:158) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:148) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:217) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:239) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:230) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:218) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:144) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.getNode(Composer.java:85) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:108) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:141) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:525) ~[patched_1.15.2.jar:git-Paper-379]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:438) ~[patched_1.15.2.jar:git-Paper-379]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:54) ~[patched_1.15.2.jar:git-Paper-379]
	... 17 more
[22:11:08] [Server thread/INFO]: [GriefPrevention] Customizable messages loaded.
[22:11:08] [Server thread/INFO]: [GriefPrevention] Successfully hooked into WorldGuard.
[22:11:08] [Server thread/INFO]: [GriefPrevention] Finished loading data (File Mode).
[22:11:08] [Server thread/INFO]: [GriefPrevention] GriefPrevention requires Vault for economy integration.
[22:11:08] [Server thread/INFO]: [GriefPrevention] Attempting to load Vault...
[22:11:08] [Server thread/INFO]: [GriefPrevention] Vault loaded successfully!
[22:11:08] [Server thread/INFO]: [GriefPrevention] Looking for a Vault-compatible economy plugin...
[22:11:08] [Server thread/INFO]: [GriefPrevention] Hooked into economy: Essentials Economy.
[22:11:08] [Server thread/INFO]: [GriefPrevention] Ready to buy/sell claim blocks!
[22:11:08] [Server thread/INFO]: [GriefPrevention] Boot finished.

**Comment by Haker519** [comment]
Ok. I got the problem. In 35 line i didnt notice indicator which was opening new maping. Was too sleepy. Fixed this. Thanks guys for help :)


By the way - if someone will need polish translation of plugin, feel free to add me at discord - Haker519#4073
